pages:
  stage: deploy
  script:
    - echo "Iniciando deploy de GitLab Pages"
    - rm -rf public
    - mkdir public
    - shopt -s extglob  # Habilita soporte para patrones extendidos en bash
    - cp -r !(public) public  # Copia todo excepto la carpeta 'public'
  artifacts:
    paths:
      - public
  only:
    - main
