pages:
  stage: deploy
  script:
    - echo "Iniciando deploy de GitLab Pages"
    - rm -rf public
    - mkdir public
    - cp -r $(ls | grep -v '^public$') public
artifacts:
  paths:
    - public
  expire_in: 1 week
only:
  - main
